# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('website_name', models.CharField(blank=True, max_length=100)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
